AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SOCRACOM button `Ring Command` system.

Globals:
  Function:
    Timeout: 10

Resources:
  Bucket:
    Type: AWS::S3::Bucket
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: build/
      Handler: app.lambda_handler
      Runtime: python3.6
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref Bucket
      Environment:
        Variables:
          BUCKET_NAME: !Ref Bucket

Outputs:
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
